### ISSUE TITLE
offer SpellCheckService implementation

### ISSUE THREAD

**Issue by miki-totefu** [CatHood0/simple_spell_checker#6]
https://api.flutter.dev/flutter/services/SpellCheckService-class.html

would make it easier to swap the default implementation for yours

Tokenizer needs to return TextRange with the match, then checkBuilder needs to return it so that the SuggestionSpan can be built as a response to fetchSpellCheckSuggestions

**Comment by CatHood0** [comment]
I know, but, i already tried the Default implementation of `SpellCheckService` and never works for me or on any device that i tried to show any misspelled word. 

By this i created this custom implementation that solves my problem. If you prefer, i think that it's better just create a new instance of same type of `SimpleSpellChecker` or `MultiSpellChecker` that works as like `SpellcheckService` using `SuggestionSpan`

If you need just the `Tokenizer` return a different type value just we can try to change the return type of `tokenize` method to be a generic.

I'll make public soon the `Checker` class to allow all devs create it's own instances like `SimpleSpellChecker` but with it's own return types and it's own implementations.

**Comment by CatHood0** [comment]
@miki-totefu please see [Release 1.2.3](https://github.com/CatHood0/simple_spell_checker/releases/tag/V1.2.3) and [Create your custom spell checker extending it from `Checker` class](https://github.com/CatHood0/simple_spell_checker/tree/V1.2.3?tab=readme-ov-file#you-can-create-your-custom-spellchecker-extending-it-from-checker-class)

I will close this issue since you can now create your own implementation of the same type of `SimpleSpellChecker` or `MultiSpellChecker` and the `Tokenizer` now support generic types. Reopen this issue if you have some issues related with the new implementation.
